// Generated by gencpp from file gmm_map_python/gmmlist.msg
// DO NOT EDIT!


#ifndef GMM_MAP_PYTHON_MESSAGE_GMMLIST_H
#define GMM_MAP_PYTHON_MESSAGE_GMMLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gmm_map_python/gmm.h>

namespace gmm_map_python
{
template <class ContainerAllocator>
struct gmmlist_
{
  typedef gmmlist_<ContainerAllocator> Type;

  gmmlist_()
    : data()  {
    }
  gmmlist_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::gmm_map_python::gmm_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gmm_map_python::gmm_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::gmm_map_python::gmmlist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_map_python::gmmlist_<ContainerAllocator> const> ConstPtr;

}; // struct gmmlist_

typedef ::gmm_map_python::gmmlist_<std::allocator<void> > gmmlist;

typedef boost::shared_ptr< ::gmm_map_python::gmmlist > gmmlistPtr;
typedef boost::shared_ptr< ::gmm_map_python::gmmlist const> gmmlistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_map_python::gmmlist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_map_python::gmmlist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gmm_map_python::gmmlist_<ContainerAllocator1> & lhs, const ::gmm_map_python::gmmlist_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gmm_map_python::gmmlist_<ContainerAllocator1> & lhs, const ::gmm_map_python::gmmlist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gmm_map_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gmm_map_python::gmmlist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_map_python::gmmlist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_map_python::gmmlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_map_python::gmmlist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_map_python::gmmlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_map_python::gmmlist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_map_python::gmmlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d72afeeabbf4ae838a844487000f2100";
  }

  static const char* value(const ::gmm_map_python::gmmlist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd72afeeabbf4ae83ULL;
  static const uint64_t static_value2 = 0x8a844487000f2100ULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_map_python::gmmlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_map_python/gmmlist";
  }

  static const char* value(const ::gmm_map_python::gmmlist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_map_python::gmmlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm[] data\n"
"\n"
"================================================================================\n"
"MSG: gmm_map_python/gmm\n"
"std_msgs/Header header\n"
"int32 mix_num\n"
"float32[] prior\n"
"float32[] x\n"
"float32[] y\n"
"float32[] z\n"
"float32[] x_var\n"
"float32[] y_var\n"
"float32[] z_var  \n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::gmm_map_python::gmmlist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_map_python::gmmlist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gmmlist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_map_python::gmmlist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_map_python::gmmlist_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gmm_map_python::gmm_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_MAP_PYTHON_MESSAGE_GMMLIST_H
