// Generated by gencpp from file gmm_map_python/SubmapList.msg
// DO NOT EDIT!


#ifndef GMM_MAP_PYTHON_MESSAGE_SUBMAPLIST_H
#define GMM_MAP_PYTHON_MESSAGE_SUBMAPLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gmm_map_python/SubmapEntry.h>

namespace gmm_map_python
{
template <class ContainerAllocator>
struct SubmapList_
{
  typedef SubmapList_<ContainerAllocator> Type;

  SubmapList_()
    : header()
    , submaps()  {
    }
  SubmapList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , submaps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gmm_map_python::SubmapEntry_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gmm_map_python::SubmapEntry_<ContainerAllocator> >::other >  _submaps_type;
  _submaps_type submaps;





  typedef boost::shared_ptr< ::gmm_map_python::SubmapList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_map_python::SubmapList_<ContainerAllocator> const> ConstPtr;

}; // struct SubmapList_

typedef ::gmm_map_python::SubmapList_<std::allocator<void> > SubmapList;

typedef boost::shared_ptr< ::gmm_map_python::SubmapList > SubmapListPtr;
typedef boost::shared_ptr< ::gmm_map_python::SubmapList const> SubmapListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_map_python::SubmapList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_map_python::SubmapList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gmm_map_python::SubmapList_<ContainerAllocator1> & lhs, const ::gmm_map_python::SubmapList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.submaps == rhs.submaps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gmm_map_python::SubmapList_<ContainerAllocator1> & lhs, const ::gmm_map_python::SubmapList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gmm_map_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gmm_map_python::SubmapList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_map_python::SubmapList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_map_python::SubmapList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_map_python::SubmapList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_map_python::SubmapList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_map_python::SubmapList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_map_python::SubmapList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59795942fabdc58b23e3562f13acfbda";
  }

  static const char* value(const ::gmm_map_python::SubmapList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59795942fabdc58bULL;
  static const uint64_t static_value2 = 0x23e3562f13acfbdaULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_map_python::SubmapList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_map_python/SubmapList";
  }

  static const char* value(const ::gmm_map_python::SubmapList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_map_python::SubmapList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"gmm_map_python/SubmapEntry[] submaps #返回所有的submap信息的列表\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gmm_map_python/SubmapEntry\n"
"#每个Submap本质上是一个key frame\n"
"\n"
"int32 robot_id\n"
"int32 submap_index # key frame 在某个机器人内部的 ID\n"
"int32 submap_version # key frame 的版本,主要是在局部轨迹内更新 key frame\n"
"geometry_msgs/Pose pose # key frame的位置, (后端优化会不断优化这个位姿)\n"
"bool is_frozen #主要是判断这个地图是否不会再更新了\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::gmm_map_python::SubmapList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_map_python::SubmapList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.submaps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmapList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_map_python::SubmapList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_map_python::SubmapList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "submaps[]" << std::endl;
    for (size_t i = 0; i < v.submaps.size(); ++i)
    {
      s << indent << "  submaps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gmm_map_python::SubmapEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.submaps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_MAP_PYTHON_MESSAGE_SUBMAPLIST_H
